name: Docs Coverage

on:
  push:
    branches:
    - current
    - main
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run coverage
        run: python3 doc_coverage_full.py
