name: Docs Coverage

on:
  push:
    branches:
      - current
      - main

  schedule:
    - cron: "0 3 * * *" # runs at 03:00 UTC

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      BQ_PROJECT_ID: vyos-billing-data
      BQ_DATASET: ci_metrics
      BQ_TABLE: docs_coverage

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-bigquery

      - name: Run docs coverage script
        run: python3 doc_coverage_full.py
